UKR_TO_ENG = {
    "січня": "january",
    "лютого": "february",
    "березня": "march",
    "квітня": "april",
    "травня": "may",
    "червня": "june",
    "липня": "july",
    "серпня": "august",
    "вересня": "september",
    "жовтня": "october",
    "листопада": "november",
    "грудня": "december",
}

RUS_TO_ENG = {
    "января": "january",
    "январь": "january",
    "февраля": "february",
    "февраль": "february",
    "марта": "march",
    "март": "march",
    "апреля": "april",
    "апрель": "april",
    "мая": "may",
    "май": "may",
    "июня": "june",
    "июнь": "june",
    "июля": "july",
    "июль": "july",
    "августа": "august",
    "август": "august",
    "сентября": "september",
    "сентябрь": "september",
    "октября": "october",
    "октябрь": "october",
    "ноября": "november",
    "ноябрь": "november",
    "декабря": "december",
    "декабрь": "december",
}