# Generated by Django 5.2.11 on 2026-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="scraping_type",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
