# Generated by Django 6.0.2 on 2026-02-15 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_session_rename_data_type_article_scraping_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
