# Generated by Django 6.0.2 on 2026-02-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0004_session_session_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(max_length=5000, unique=True),
        ),
    ]
