# Generated by Django 6.0.2 on 2026-02-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_article_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_status',
        ),
    ]
