# Generated by Django 6.0.2 on 2026-02-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0007_site_package"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="retries",
            field=models.IntegerField(default=0),
        ),
    ]
