# Generated by Django 6.0.2 on 2026-02-19 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0009_site_timezone"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("NSTBROWSER", "NSTBROWSER"),
                            ("MULTILOGIN", "MULTILOGIN"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("profile_id", models.CharField(max_length=255)),
                ("folder_id", models.CharField(blank=True, max_length=255, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "browser_profile",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="scraping_type",
            field=models.CharField(
                choices=[("NEWS", "NEWS"), ("ARTICLES", "ARTICLES")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="url",
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name="rawresponsedata",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="rawresponsedata",
            name="scraping_type",
            field=models.CharField(
                choices=[("NEWS", "NEWS"), ("ARTICLES", "ARTICLES")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="rawresponsedata",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_responses",
                to="src.session",
            ),
        ),
        migrations.AlterField(
            model_name="rawresponsedata",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="raw_responses",
                to="src.site",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="error_msg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="session",
            name="retries",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="session",
            name="scraping_type",
            field=models.CharField(
                choices=[("NEWS", "NEWS"), ("ARTICLES", "ARTICLES")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "CREATED"),
                    ("RUNNING", "RUNNING"),
                    ("SUCCESS", "SUCCESS"),
                    ("FAILED", "FAILED"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="total_saved",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="session",
            name="traceback_msg",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="site",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["site", "scraping_type"], name="article_site_id_09a252_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["published_at"], name="article_publish_ce9565_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawresponsedata",
            index=models.Index(
                fields=["site", "scraping_type"], name="raw_respons_site_id_11a53a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawresponsedata",
            index=models.Index(
                fields=["session", "url"], name="raw_respons_session_a004b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["scraping_type"], name="session_scrapin_d8b708_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="session",
            index=models.Index(
                fields=["status", "created_at"], name="session_status_18ad70_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.UniqueConstraint(
                fields=("url",), name="unique_article_url"
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                condition=models.Q(("scraping_type__in", ["NEWS", "ARTICLES"])),
                name="article_scraping_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawresponsedata",
            constraint=models.CheckConstraint(
                condition=models.Q(("scraping_type__in", ["NEWS", "ARTICLES"])),
                name="raw_response_data_scraping_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(("scraping_type__in", ["NEWS", "ARTICLES"])),
                name="session_scraping_type_valid",
            ),
        ),
        migrations.AddField(
            model_name="browserprofile",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="browser_profiles",
                to="src.site",
            ),
        ),
        migrations.AddIndex(
            model_name="browserprofile",
            index=models.Index(
                fields=["site", "provider"], name="browser_pro_site_id_b163b6_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="browserprofile",
            constraint=models.UniqueConstraint(
                fields=("site", "provider"), name="unique_browser_profile"
            ),
        ),
        migrations.AddConstraint(
            model_name="browserprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider__in", ["NSTBROWSER", "MULTILOGIN"])),
                name="browser_provider_valid",
            ),
        ),
    ]
