# Generated by Django 6.0.2 on 2026-02-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_alter_browserprofile_extra_data'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['CREATED', 'RUNNING', 'SUCCESS', 'FAILED'])), name='session_status_valid'),
        ),
    ]
