# Generated by Django 6.0.2 on 2026-02-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0012_session_session_status_valid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="subtitle",
            field=models.TextField(blank=True, null=True),
        ),
    ]
